const ShopActionTypes = { 
    FETCH_COLLECNTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FECH_COLLECTIONS_FAILURE'
}

export default ShopActionTypes;